require:
  - rubocop-performance

inherit_mode:
  merge:
    - Include
    - Exclude
    - AllowedNames

AllCops:
  Exclude:
    - "bin/*"
    - "gemfiles/*"
  TargetRubyVersion: 2.5

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementLineBreak:
  Enabled: true # default: false

Layout/FirstHashElementLineBreak:
  Enabled: true # default: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: true # default: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true # default: false
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Lint/SuppressedException:
  AllowComments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/AbcSize:
  Enabled: false # default: true

Metrics/LineLength:
  Max: 120 # default: 80
  IgnoredPatterns:
    - "^ *#" # comments

Metrics/BlockLength:
  Enabled: false # default: true
  Exclude:
    - "config/routes.rb"
    - "config/routes/*"
    - "lib/tasks/**/*"
    - "Guardfile"

Metrics/ClassLength:
  Enabled: false # default: true

Metrics/CyclomaticComplexity:
  Enabled: false # default: true

Metrics/MethodLength:
  Enabled: false # default: true

Metrics/ModuleLength:
  Enabled: false # default: true

Metrics/PerceivedComplexity:
  Enabled: false # default: true

Naming/AccessorMethodName:
  Enabled: false # default: true

Naming/MethodParameterName:
  AllowedNames:
    - as

Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/ChainArrayAllocation:
  Enabled: true # default: false

Performance/OpenStruct:
  Enabled: true # default: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false # default: true

Style/AutoResourceCleanup:
  Enabled: true # default: false

Style/DateTime:
  Enabled: true # default: false

Style/CollectionMethods:
  Enabled: true # default: false

Style/Documentation:
  Enabled: false # default: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/MethodCalledOnDoEndBlock:
  Enabled: true # default: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/ReturnNil:
  Enabled: true # default: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
