AllCops:
  Exclude:
    - 'bin/*'
  TargetRubyVersion: 2.3

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Layout/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Lint/EndAlignment:
  AutoCorrect: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/AbcSize:
  Enabled: false # todo
  Max: 20 # default: 15

Metrics/BlockLength:
  Enabled: false # todo

Metrics/CyclomaticComplexity:
  Enabled: false # todo
  Max: 10 # default: 6

Metrics/LineLength:
  Enabled: true
  Max: 100 # default: 80
  IgnoredPatterns:
    - "^ *#" # comments

Metrics/MethodLength:
  Enabled: false # todo
  Exclude:
    - "db/migrate/*"
  Max: 12 # default: 10

Metrics/PerceivedComplexity:
  Enabled: false # todo
  Max: 10 # default: 7

Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/HashEachMethods:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  Enabled: false

Style/Dir:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"
    - "config/routes/*"

Style/FrozenStringLiteralComment:
  Enabled: false # we'll do later

Style/Lambda:
  Enabled: false


Style/MethodCallWithArgsParentheses:
  Enabled: true # false by default
  Exclude:
    - "Gemfile"
  IgnoreMacros: true
  IgnoredMethods:
    - include
    - load
    - print
    - private
    - protected
    - public
    - puts
    - raise
    - require
    - require_relative
    # rake
    - desc
    - namespace
    - task

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

#
# Temporary disabled
#

Layout/EmptyLinesAroundArguments:
  Enabled: false # buggy yet

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ExtendSelf:
  Enabled: false

Style/FormatStringToken:
  Enabled: false # issue with strftime

Style/GuardClause:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StructInheritance:
  Enabled: false
