AllCops:
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'
  TargetRubyVersion: 2.3

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Layout/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Lint/RedundantWithIndex:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/AbcSize:
  Enabled: true
  Max: 20 # default: 15

Metrics/BlockLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10 # default: 6

Metrics/LineLength:
  Enabled: true
  Max: 100 # default: 80
  IgnoredPatterns:
    - "^ *#" # comments

Metrics/MethodLength:
  Enabled: false
  Max: 12 # default: 10

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10 # default: 7

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Dir:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true # false by default
  Exclude:
    - "Gemfile"
  IgnoreMacros: true
  IgnoredMethods:
    - include
    - load
    - print
    - private
    - protected
    - public
    - puts
    - raise
    - require
    - require_relative
    # rake
    - desc
    - namespace
    - task

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/ReturnNil:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
