language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
bundler_args: --without local
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake ci
