before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without local
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
script:
  - bundle exec rake ci
