name: Test

on: [push, pull_request]

jobs:
  build:
    name: on ruby ${{matrix.ruby}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, head]
        gemfiles: ['gemfiles/rails42.gemfile', 'gemfiles/rails50.gemfile', 'gemfiles/rails51.gemfile', 'gemfiles/rails52.gemfile', 'gemfiles/rails60.gemfile']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Specs
      run: bundle exec rake ci
